using Microsoft.EntityFrameworkCore;
using worksheet2.Model;

namespace worksheet2.Data
{
    /**
     * Defines the tables and their constrains for the database 
     */
    public class BankContext : DbContext
    {
        public BankContext(DbContextOptions<BankContext> options) : base(options)
        {
        }

        public DbSet<User> Users { get; set; }
        public DbSet<UserDetails> UserDetails { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<AccountDetails> AccountDetails { get; set; }

        protected override void OnModelCreating(
            ModelBuilder modelBuilder
        )
        {
            MakePrimaryKeyAutoGenerated(modelBuilder);

            MakeFieldsUnique(modelBuilder);

            ManageRelationShip(modelBuilder);
        }

        /**
         * Defines the relationship of tables
         */
        private static void ManageRelationShip(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<User>()
                .HasMany(user => user.AccountDetails);

            modelBuilder
                .Entity<User>()
                .HasOne(u => u.UserDetails)
                .WithOne(details => details.User)
                .HasForeignKey<UserDetails>();

            modelBuilder
                .Entity<User>()
                .HasMany(u => u.Transactions);
        }

        /**
         * Defines the column to be unique 
         */
        private static void MakeFieldsUnique(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<User>()
                .HasIndex(user => user.UserName)
                .IsUnique();

            modelBuilder
                .Entity<User>()
                .HasIndex(user => user.AccountNumber)
                .IsUnique();

            modelBuilder
                .Entity<AccountDetails>()
                .HasIndex(details => details.UserAccountDetailsId)
                .IsUnique();
        }

        /**
         * Makes the primary keys auto generated when new entries are added
         */
        private static void MakePrimaryKeyAutoGenerated(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(u => u.UserId)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<UserDetails>()
                .Property(u => u.UserUserDetailsId)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<Transaction>()
                .Property(t => t.UserTransactionId)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<AccountDetails>()
                .Property(ac => ac.UserAccountDetailsId)
                .ValueGeneratedOnAdd();
        }
    }
}